void insert_song(struct song_node *, struct song_node *[]);
struct song_node * find(struct song_node*, struct song_node *[]);
struct song_node * find_list(struct song_node *, struct song_node *);
struct song_node * find_artist(struct song_node *, struct song_node *[]);
void print_artist(struct song_node *, struct song_node *[]);
struct song_node * find_artist_list(struct song_node *, struct song_node *);
void print_letter(char, struct song_node *[]);
void print_library(struct song_node *[]);
void delete_song(struct song_node *, struct song_node *[]);
struct song_node* delete_song_list(struct song_node *, struct song_node *);
void delete_all(struct song_node *[]);
void shuffle(struct song_node *[]);
void print_rand(struct song_node *);
